CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lon FLOAT                                   NOT NULL,
    lat FLOAT                                   NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    annotation          VARCHAR                                 NOT NULL,
    description         VARCHAR                                 NOT NULL,
    created             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    eventDate           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid                BOOLEAN                                 NOT NULL,
    locationID          BIGINT,
    initiatorID         BIGINT                                  NOT NULL,
    categoryID          BIGINT                                  NOT NULL,
    participantLimit    INT,
    requestModeration   BOOLEAN                                 NOT NULL,
    published           TIMESTAMP WITHOUT TIME ZONE,
    state               VARCHAR,

    CONSTRAINT pk_events PRIMARY KEY (id),
    FOREIGN KEY (initiatorID) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (categoryID) REFERENCES categories (id) ON DELETE CASCADE,
    FOREIGN KEY (locationID) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    eventID         BIGINT                                  NOT NULL,
    requesterID     BIGINT                                  NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status          VARCHAR,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    FOREIGN KEY (requesterID) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (eventID) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilationID BIGINT NOT NULL,
    eventID       BIGINT NOT NULL,
    CONSTRAINT pk_comp_event PRIMARY KEY (compilationID, eventID),
    FOREIGN KEY (eventID) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (compilationID) REFERENCES compilations (id) ON DELETE CASCADE
);
